import { z } from 'zod';
import { createZodDto } from 'nestjs-zod';

export const ReadProductSchema = z.object({
  productId: z.string().optional(), // This is optional because it is generated by the database
  productCategory: z.string(),
  productName:  z.string(),
  price: z.number(),
  description: z.string().optional(),
  stock:z.number(),
});


export type ReadProductType = z.infer<typeof ReadProductSchema>;
export class ReadProductDTO extends createZodDto(ReadProductSchema) {}
